#!/usr/bin/env python3
# coding: utf8

import lib
from lib import adb
import sys, os

if __name__ == '__main__':
    import getopt
    optlist, args = getopt.getopt(sys.argv[1:], 's:')
    for optkey, optvalue in optlist:
        if optkey == '-s':
            serial_no = optvalue
            break
    else:
        serial_no = ''
    Adb.SERIAL_NO = adb.select_device(serial_no)

    device = Device()

    partitions = device.get_partitions()
    available_args = ('all', ) + tuple(partitions.keys())

    if set(args) - set(available_args) or not args:
        print('Usage: %s %s'%(sys.argv[0], available_args))
        sys.exit(1)

    device.check_partition_files(args)

    with Downloader(device) as down:
        if 'all' in args:
            device.write_all()
        else:
            for part in args:
                device.write(part)

